apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fl-dataset
  namespace: vmware-rapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
