apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: aggregator
  namespace: {{ .Values.namespace }}
=======
  name: fl-server
  namespace: vmware-rapps
>>>>>>> master
spec:
  ports:
    - protocol: TCP
      port: 51000
      targetPort: 51000
  selector:
<<<<<<< HEAD
    app: aggregator
=======
    app: fl-server
>>>>>>> master
