apiVersion: v1
kind: Service
metadata:
  name: aggregator
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: 51000
      targetPort: 51000
  selector:
    app: aggregator
