# Default values for oran_tp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageName: hoangtuansu/rapp_tp:0.9
namespace: ets-admin
bootstrap_url: http://10.180.113.114:8080
clients:
  - name: client1
    cells: '1001'
    port: 31908
  - name: client2
    cells: '1002'
    port: 31909
  - name: client3
    cells: '1003'
    port: 31910
  - name: client4
    cells: '1004'
    port: 31911